# Generated by Django 6.0.4 on 2026-04-20 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_remove_produto_disponivel_loja_logo_alter_loja_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='cor_principal',
            field=models.CharField(default='#10b981', max_length=20),
        ),
    ]
