# Generated by Django 6.0.4 on 2026-04-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0003_loja_cor_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='mais_vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_promocional',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
