# Generated by Django 6.0.4 on 2026-04-20 02:22

import lojas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0004_produto_mais_vendido_produto_preco_promocional'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='senha_admin',
            field=models.CharField(default=lojas.models.gerar_senha, max_length=6),
        ),
    ]
