# Generated by Django 6.0.1 on 2026-04-23 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0006_indicacao_pedido_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='notificado_recuperacao',
            field=models.BooleanField(default=False),
        ),
    ]
