# Generated by Django 6.0.1 on 2026-04-23 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0007_loja_notificado_recuperacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loja',
            name='notificado_recuperacao',
        ),
    ]
